### ISSUE TITLE
Issue with convert-if-else-to-conditional-expression

### ISSUE THREAD

**Issue by chandan192** [p42ai/js-assistant#56]
Hi @lgrammel , 
Hope you are doing well. I got an issue with **convert-if-else-to-conditional-expression**. 
![image](https://user-images.githubusercontent.com/36302444/200185647-2538278d-6324-4948-b605-fbb0ccf9343e.png)

After applying the suggestion **convert to conditional expression** which was marked safe
![image](https://user-images.githubusercontent.com/36302444/200185669-4eca6e2a-1741-4ce7-af36-141a59e7567b.png)

**Comment by lgrammel** [comment]
Hi @chandan192 - thanks for the bug report! I've just released `v1.163.2`, which fixes the issue. Please re-open if you still encounter it in the new version.
