### ISSUE TITLE
Cannot pass the payment process on the select country window

### ISSUE THREAD

**Issue by Jakub41** [p42ai/js-assistant#58]
Hello,

I'm trying to get into the payment process and I'm selecting my location in Denmark and all I see is that

<img width="401" alt="CleanShot 2022-11-14 at 20 58 26@2x" src="https://user-images.githubusercontent.com/8559542/201754787-16579d00-8187-42fa-aa78-33dbb1713e4b.png">

I have an internet connection and I saw if I switch to Italy for example there seems to work.

Why for DK no?

Thank you for your help

**Comment by lgrammel** [comment]
Hi Jakub, thanks for your notification, this is good to know. I'm using Paddle as a Payment provider and I'm not sure why this is happening - presumably it's an issue on their end. I'll close this ticket for now.

**Comment by lgrammel** [comment]
Awesome - thanks for your support!
