### ISSUE TITLE
Insert console.log for variable

### ISSUE THREAD

**Issue by chandan192** [p42ai/js-assistant#63]
Hi @lgrammel , 
Code action for inserting console.log is not showing up. Have we removed the support.

![Peek 2022-12-04 15-53](https://user-images.githubusercontent.com/36302444/205485546-9a93df2a-3ded-4732-bee1-4a8f796766be.gif)

**Comment by lgrammel** [comment]
Hey @chandan192 - it is available on the "Other action" shortcut ( https://p42.ai/documentation/p42-for-vscode/editor-integration#keyboard-shortcuts ).

**Comment by chandan192** [comment]
Okay, thanks @lgrammel
